import type { Metadata } from "next";
import './globals.css'
import { Geist, Geist_Mono } from "next/font/google";
import AuthProvider from "@/context/authProvider";
import { Toaster } from "@/components/ui/sonner" 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "True Feedback",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-900`}>
          {children}
          <Toaster />
        </body>
      </AuthProvider>
    </html>
  );
}
